### ISSUE TITLE
Option to disable sorting

### ISSUE THREAD

**Issue by asgeo1** [gennaro-tedesco/nvim-jqix#14]
Hello, I just tried this plugin out.

The first thing that confused me, was that the json keys seem sorted alphabetically by default. I wasn't expecting this, and I found it disorientating when navigating the properties. I feel like it should match the source.

Is it possible to have an option that doesn't sort the keys?

**Comment by gennaro-tedesco** [comment]
Good point. At the moment I rely on `jq 'keys'`, which by default sorts the keys alphabetically without presenting a choice; however, it seems that starting from `jq-1.5` a new option `keys_unsorted` was introduced, so this may just do very simply. I will look at it in these days, seeing if it conflicts with other parts of the plugin.

Thank you for the suggestion, definitely something to implement one way or the other.

**Comment by gennaro-tedesco** [comment]
I have drafted an implementation in [this PR](https://github.com/gennaro-tedesco/nvim-jqx/pull/15): it seems to be doing the job.

Please help me test it: install the specific branch (according to the plugin manager you are using there are ways to do so, for instance if you are using vim-plug [here's how](https://github.com/junegunn/vim-plug#example)) and then simply specify in your configuration (say your `init.vim` or equivalent)
```
lua require('nvim-jqx.config').sort = false
```

https://user-images.githubusercontent.com/15387611/125308395-29419a80-e331-11eb-88f6-a46b3539dc66.mov

**Comment by asgeo1** [comment]
Thanks for that!  Yes, it works for me :-)

**Comment by gennaro-tedesco** [comment]
The PR is merged: simply `:PlugUpdate` (or equivalent) your configuration to have it work.

P. S. Notice I made a little last minute change: default is [lua require('nvim-jqx.config').sort=true](https://github.com/gennaro-tedesco/nvim-jqx/blob/57f5a51d8febce0ad1c7679ee7039504e5693976/lua/nvim-jqx/config.lua#L9) to avoid that people who do not have the latest version of `jq` run into problems before they even start using the plugin :). This means that in order to have your behaviour you must explicitly include 
```
lua require('nvim-jqx.config').sort = false
```
in your config.
